all:
	make -f ../encoder/Makefile all
	#cp dspcreate /usr/local/bin
	#cp libavdspencoder.dylib /usr/local/lib
	make -f ../dspprogs/Makefile all
#	make -f oktodac.mak all

clean:
	make -f ../encoder/Makefile clean
	make -f ../dspprogs/Makefile clean
	