all:
	make -f ../encoder/Makefile all
	@echo dspcreate done, type your password to copy to /usr/local/bin, otherwise Ctrl C
	sudo cp dspcreate /usr/local/bin
#	cp libavdspencoder.dylib /usr/local/lib
#	make -f ../dspprogs/Makefile all
#	make -f oktodac.mak all

clean:
	make -f ../encoder/Makefile clean
#	make -f ../dspprogs/Makefile clean
	